language: rust
rust:
  - stable
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
git:
  depth: 5
addons:
  apt:
    # Ubuntu
    packages: libudev-dev libasound2-dev wireshark libglib2.0-dev
    update: true
  #homebrew:
  # https://docs.travis-ci.com/user/installing-dependencies#installing-packages-on-macos
