[package]
name = "conway"
version = "0.1.2"
authors = ["Aaron Miller <aaron.miller04@gmail.com>", "mang"]
license = "GPL-3.0+"
description = "library for multi-player game of life ConWaysteTheEnemy"

[dependencies]
rand = "0.3"
