[package]
name = "conway"
version = "0.1.3"
authors = ["Aaron Miller <aaron.miller04@gmail.com>", "mang"]
license = "GPL-3.0+"
description = "library for multi-player game of life ConWaysteTheEnemy"

[[bin]]
name = "main"
doc = false

[dependencies]
env_logger = "0.3"
log        = "0.3"
rand       = "0.3"
