[package]
name = "ConWaysteTheEnemy"
version = "0.0.1"
authors = [ "mang", "Aaron Miller <aaron.miller04@gmail.com>" ]

[dependencies]
conway = { git = "https://github.com/AaronM04/libconway" }
mioco = "*"
conrod = "0.46.2"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
