[package]
name = "ConWaysteTheEnemy"
version = "0.0.2"
authors = [ "mang", "Aaron Miller <aaron.miller04@gmail.com>" ]
license = "GPL-3.0+"

[dependencies]
conway = "0.1.2"  # { git = "https://github.com/AaronM04/libconway" }
ggez = "0.2.1"
env_logger = "0.3"
log = "0.3"
sdl2-sys = "0.25.0"
sdl2 = "0.25.0"
version = "2.0.1"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
