[package]
name = "conwayste"
version = "0.0.3"
authors = [ "mang", "Aaron Miller <aaron.miller04@gmail.com>" ]
license = "GPL-3.0+"

[dependencies]
conway     = "0.1.3"  # { git = "https://github.com/conwayste/libconway" } # { path = "../libconway" }
ggez       = "0.2.2"
env_logger = "0.3"
log        = "0.3"
sdl2       = "0.27.3"
version    = "2.0.1"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
