[package]
name = "conwayste"
version = "0.0.4"
authors = [ "Ameen Manghi <manghirs@gmail.com>", "Aaron Miller <aaron.miller04@gmail.com>" ]
license = "GPL-3.0+"

[dependencies]
conway       = { git = "https://github.com/conwayste/libconway" }
ggez         = "0.4"
env_logger   = "0.3"
log          = "0.3"
sdl2         = "0.30.0"
version      = "2.0.1"
toml         = "0.4.5"
serde        = "1.0"
serde_derive = "1.0"

[profile.dev]
opt-level = 2

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
