[package]
name = "conwayste"
version = "0.2.0"
authors = [ "Ameen Manghi <manghirs@gmail.com>", "Aaron Miller <aaron.miller04@gmail.com>" ]
license = "GPL-3.0+"
edition = "2018"

[dependencies]
conway       = { path = "../libconway" }
netwayste    = { path = "../netwayste" }
downcast-rs  = "1.0.4"
ggez         = "0.5"
log          = "0.4.6"
chrono       = "0.4.6"
env_logger   = "0.6.1"
version      = "2.0.1"
toml         = "0.5"
serde        = {version="1.0.90", features=["derive"]}
rand         = "0.4"
futures      = "0.1.17"
tokio-core   = "0.1.9"
color-backtrace = "0.1"
lazy_static  = "1.2"
chromatica   = "1.0.1"
custom_error = "1.4"

[[bin]]
name = "client"
path = "src/client.rs"
