[package]
name = "conwayste"
version = "0.3.2-alpha3"
authors = [ "Ameen Manghi <manghirs@gmail.com>", "Aaron Miller <aaron.miller04@gmail.com>" ]
license = "GPL-3.0+"
edition = "2018"

[dependencies]
chromatica   = "1.0.1"
chrono       = "0.4.6"
color-backtrace = "0.1"
conway       = { path = "../libconway" }
custom_error = "1.4"
downcast-rs  = "1.0.4"
env_logger   = "0.6.1"
futures      = "0.1.17"
ggez         = "0.5"
id_tree      = "1.7.0"
lazy_static  = "1.3"
log          = "0.4.6"
netwayste    = { path = "../netwayste" }
rand         = "0.4"
serde        = {version="1.0.90", features=["derive"]}
tokio-core   = "0.1.9"
toml         = "0.5"
version      = "2.0.1"

[[bin]]
name = "client"
path = "src/client.rs"
