[package]
name = "netwayste"
version = "0.3.5"
authors = ["Aaron Miller <aaron.miller04@gmail.com>", "manghi <manghirs@gmail.com>"]
edition = "2018"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
futures              = "0.1.17"
tokio-core           = "0.1.9"
log                  = "0.4.8"
chrono               = "0.4.11"
env_logger           = "0.7.1"
serde                = {version="1.0.90", features=["derive"]}
bincode              = "0.9.2"
base64               = "0.12.1"
rand                 = "0.7.3"
time                 = "0.1"
semver               = "0.10.0"
tokio-dns-unofficial = "0.4"
regex                = "1"
clap                 = "2"
color-backtrace      = "0.1"

[dev-dependencies]
proptest             = "0.10"
