[package]
name = "dissect-netwayste"
version = "0.1.0"
authors = ["Aaron Miller <aaron.miller04@gmail.com>"]
edition = "2018"

[dependencies]
netwayste   = { path = "../netwayste" }
lazy_static = "1.3.0"

[build-dependencies]
bindgen = "0.49.0"

[lib]
crate-type = ["cdylib"]
